### PR TITLE
Fixed error and made SQS resources external to the application.

### PR DESCRIPTION
**Pull request by mkrauklis**
Issue #2 

Fixed error that was causing the Lambda function to fail.
Removed SQS resources from the template and replaced them with parameters to reference external resources.

### CODE REVIEW

**Comment by AlexPinhel** [comment]
Thanks @mkrauklis! for the suggestions and updates. Merged.

**Comment by mkrauklis** [comment]
My pleasure, thanks for the quick turn-around @AlexPinhel. Question: do you have a process for getting this updated in the AWS Serverless Application Repository? I'd like to reference this as an application rather than having to pull the code into many projects.

**Comment by edank** [comment]
Do these changes recommend against using the template to create the 3 SQS queues or just offering another option?

**Comment by mkrauklis** [comment]
@edank Correct, the changes are under the recommendation that the application not make the queues and they be created externally.

**Pull request merged**
